language: node_js
node_js:
  - 0.12
  - 4
  - 5

sudo: false

#before_script:
#  - npm install -g grunt-cli

install:
  - npm install

script:
  - npm run lint
  - npm run test-cov

branches:
  only:
    - gh-pages
#after_success:
#    - npm run coveralls

#after_success:
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
